version: '3'

services:   
  graphql:
    container_name: graphql
    build: ./dockerfiles/graphql
    tty: true
    restart: always
    volumes:
      - ./dockerfiles/graphql/graphql:/graphql
        # - type: bind
        #   source: ./dockerfiles/graphql/graphql
        #   target: /graphql
    ports:
      - '4000:4000'